/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom4app;

import java.sql.ResultSet;

/**
 *
 * @author Zero
 */
public class Mainform extends javax.swing.JFrame {

    /**
     * Creates new form Mainform
     */
    public Mainform() {
        initComponents();
        DBAccess dba = new DBAccess();
        String query = "Select * From type";
        ResultSet rs = dba.Query(query);
        try {
            while (rs.next()) {
                cb_Currency.addItem(rs.getString("Name"));
            }
        } catch (Exception e) {
        }
        txt_result.setLineWrap(true);
        txt_result.setWrapStyleWord(true);
    }

    String Numb = "";
    String Input = "";

    public void Button(String Num) {
        txt_result.setText("");
        Numb = Numb + Num;
        Input = "Price:          " + Numb + " " + cb_Currency.getSelectedItem();
        txt_input.setText(Input);
        countCurrency(Numb);
    }

    public void countCurrency(String Numb) {
        DBAccess dba = new DBAccess();
        String[] result = new String[200];
        int amount = Integer.parseInt(Numb);
        int token = amount;
//        String query = "Select * From money where Type= '" + cb_Currency.getSelectedIndex() + "'";
        String query = "Select * From type where Id= '0'";
        ResultSet rs = dba.Query(query);
        try {
            System.out.println(rs.getString("Name"));
//            Integer [] notes = {rs.getInt("Note")};
//            Arrays.sort(notes, Collections.reverseOrder());
//            int[] noteCounter = new int[notes.length];
//
//            // count notes using Greedy approach
//            for (int i = 0; i < notes.length; i++) {
//                if (token >= notes[i]) {
//                    noteCounter[i] = amount / notes[i];
//                    amount = amount % notes[i];
//                }
//            }
//
//            // Print notes
//            for (int i = 0; i < notes.length; i++) {
//                if (token >= notes[i]) {
//                    result[i] = cb_Currency.getSelectedItem()+" " + notes[i] + " : " + noteCounter[i] + "\t";
//                    txt_result.append(result[i]);
//
//                }
//            }
        } catch (Exception e) {
            System.out.println("NO");
        }

//        int[] notes = new int[]{500000, 200000, 100000, 50000, 20000, 10000, 5000, 2000, 1000};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Zero = new javax.swing.JButton();
        Btn_Clear = new javax.swing.JButton();
        Btn_Four = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_result = new javax.swing.JTextArea();
        txt_input = new javax.swing.JTextField();
        cb_Currency = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Btn_Three = new javax.swing.JButton();
        Btn_One = new javax.swing.JButton();
        Btn_Two = new javax.swing.JButton();
        Btn_Five = new javax.swing.JButton();
        Btn_Six = new javax.swing.JButton();
        Btn_Seven = new javax.swing.JButton();
        Btn_Eight = new javax.swing.JButton();
        Btn_Nine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_Zero.setText("0");
        Btn_Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ZeroActionPerformed(evt);
            }
        });

        Btn_Clear.setText("CLEAR");
        Btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ClearActionPerformed(evt);
            }
        });

        Btn_Four.setText("4");
        Btn_Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FourActionPerformed(evt);
            }
        });

        txt_result.setEditable(false);
        txt_result.setColumns(20);
        txt_result.setRows(5);
        jScrollPane1.setViewportView(txt_result);

        txt_input.setEditable(false);
        txt_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cb_Currency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CurrencyActionPerformed(evt);
            }
        });

        jButton1.setText("Setting");

        Btn_Three.setText("3");
        Btn_Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ThreeActionPerformed(evt);
            }
        });

        Btn_One.setText("1");
        Btn_One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OneActionPerformed(evt);
            }
        });

        Btn_Two.setText("2");
        Btn_Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TwoActionPerformed(evt);
            }
        });

        Btn_Five.setText("5");
        Btn_Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_FiveActionPerformed(evt);
            }
        });

        Btn_Six.setText("6");
        Btn_Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SixActionPerformed(evt);
            }
        });

        Btn_Seven.setText("7");
        Btn_Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SevenActionPerformed(evt);
            }
        });

        Btn_Eight.setText("8");
        Btn_Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EightActionPerformed(evt);
            }
        });

        Btn_Nine.setText("9");
        Btn_Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_Currency, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(txt_input))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Nine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Five, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_One, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn_Six, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_Seven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Btn_Eight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Four, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_Currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Three, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_One, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Two, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Four, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Five, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Six, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Seven, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Eight, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Nine, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Zero, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ZeroActionPerformed
        Button("0");
    }//GEN-LAST:event_Btn_ZeroActionPerformed

    private void Btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ClearActionPerformed
        Numb = "";
        txt_input.setText("Price:          0 " + cb_Currency.getSelectedItem());
        txt_result.setText("");
    }//GEN-LAST:event_Btn_ClearActionPerformed

    private void Btn_FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FourActionPerformed
        Button("4");
    }//GEN-LAST:event_Btn_FourActionPerformed

    private void cb_CurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CurrencyActionPerformed
        txt_input.setText("Price:          0 " + cb_Currency.getSelectedItem());
        txt_result.setText("");
    }//GEN-LAST:event_cb_CurrencyActionPerformed

    private void Btn_ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ThreeActionPerformed
        Button("3");
    }//GEN-LAST:event_Btn_ThreeActionPerformed

    private void Btn_OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OneActionPerformed
        Button("1");
    }//GEN-LAST:event_Btn_OneActionPerformed

    private void Btn_TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TwoActionPerformed
        Button("2");
    }//GEN-LAST:event_Btn_TwoActionPerformed

    private void Btn_FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_FiveActionPerformed
        Button("5");
    }//GEN-LAST:event_Btn_FiveActionPerformed

    private void Btn_SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SixActionPerformed
        Button("6");
    }//GEN-LAST:event_Btn_SixActionPerformed

    private void Btn_SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SevenActionPerformed
        Button("7");
    }//GEN-LAST:event_Btn_SevenActionPerformed

    private void Btn_EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EightActionPerformed
        Button("8");
    }//GEN-LAST:event_Btn_EightActionPerformed

    private void Btn_NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NineActionPerformed
        Button("9");
    }//GEN-LAST:event_Btn_NineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Clear;
    private javax.swing.JButton Btn_Eight;
    private javax.swing.JButton Btn_Five;
    private javax.swing.JButton Btn_Four;
    private javax.swing.JButton Btn_Nine;
    private javax.swing.JButton Btn_One;
    private javax.swing.JButton Btn_Seven;
    private javax.swing.JButton Btn_Six;
    private javax.swing.JButton Btn_Three;
    private javax.swing.JButton Btn_Two;
    private javax.swing.JButton Btn_Zero;
    private javax.swing.JComboBox<String> cb_Currency;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_input;
    private javax.swing.JTextArea txt_result;
    // End of variables declaration//GEN-END:variables
}
