///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package nhom4app;
//
//import java.security.MessageDigest;
//import java.security.NoSuchAlgorithmException;
//import java.sql.ResultSet;
//import java.util.Date;
//import java.util.Properties;
//import java.util.Random;
//import javax.mail.Message;
//import javax.mail.Multipart;
//import javax.mail.PasswordAuthentication;
//import javax.mail.Session;
//import javax.mail.Transport;
//import javax.mail.internet.InternetAddress;
//import javax.mail.internet.MimeBodyPart;
//import javax.mail.internet.MimeMessage;
//import javax.mail.internet.MimeMultipart;
//import javax.swing.JOptionPane;
//
///**
// *
// * @author legia
// */
//public class Register extends javax.swing.JFrame {
//
//    /**
//     * Creates new form Register
//     */
//    public Register() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tf_Username = new javax.swing.JTextField();
        tf_Email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_SignUp = new javax.swing.JButton();
        btn_Return = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_Lname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_Fname = new javax.swing.JTextField();
        tf_Pass = new javax.swing.JPasswordField();
        tf_confirm = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Register");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));
        getContentPane().add(tf_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 210, -1));
        getContentPane().add(tf_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Confirm password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btn_SignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SignUp.setText("Save");
        btn_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 70, -1));

        btn_Return.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Return.setText("Return");
        btn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 256, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Last name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(tf_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("First name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(tf_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, -1));
        getContentPane().add(tf_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 210, -1));
        getContentPane().add(tf_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/anhnen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    
//    Random rand = new Random();    
//    int ran = rand.nextInt((9999 - 100) + 1);
//    
//    
//    private String OTPN(){
//        return Integer.toString(ran);
//    }
//    
    private void btn_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SignUpActionPerformed
//        String Lname = this.tf_Lname.getText();
//        String Fname = this.tf_Fname.getText();
//        String Email = this.tf_Email.getText();
//        String username = this.tf_Username.getText();
//        String pass1 = new String(this.tf_Pass.getPassword());
//        String pass2 = new String(this.tf_confirm.getPassword());
//        if (Lname.equals("")) {
//            JOptionPane.showMessageDialog(null, "Last name cannot be empty!");
//        } else {
//            if (Fname.equals("")) {
//                JOptionPane.showMessageDialog(null, "First name cannot be empty!");
//            } else {
//                if (username.equals("")) {
//                    JOptionPane.showMessageDialog(null, "Username cannot be empty!");
//                } else {
//                    if (Email.equals("")) {
//                        JOptionPane.showMessageDialog(null, "Email cannot be empty!");
//                    } else {
//                        if (pass1.equals("")) {
//                            JOptionPane.showMessageDialog(null, "Password cannot be empty!");
//                        } else {
//                            if (pass2.equals("")) {
//                                JOptionPane.showMessageDialog(null, "Need to comfirm password!");
//                            } else {
//                                if (pass2.equals(pass1)) {
//                                    DBAccess acc = new DBAccess();
//                                    
//                                    String query = "Select * "
//                                            + "From account"
//                                            + " Where Acc_Name='" + username + "' OR Email='" + Email + "'";
//                                    ResultSet rs = acc.Query(query);
//                                    try {
//                                        if (!rs.next()) {
//                                            String query1 = "insert into account (Acc_Name, Pass, Email)"
//                                                    + "values('" + username + "' ,'" + Encrypt(pass1) + "', '" + Email + "')";
//                                            acc.Update(query1);
//
//                                            String query2 = "insert into user (	User_ID, Lname, Fname, User_Name, Email)"
//                                                    + "values('" + "0" + "', '" + Lname + "', '" + Fname + "', '" + username + "', '" + Email + "')";
//                                            int result = acc.Update(query2);
//                                            if (result == 0) {
//                                                JOptionPane.showMessageDialog(null, "Register Fail!");
//                                                return;
//                                            }
//                                            JOptionPane.showMessageDialog(null, "Register Successfull");
//                                            new login().setVisible(true);
//                                            dispose();
//                                        } else {
//                                            JOptionPane.showMessageDialog(null, "This account have been registered!");
//                                        }
//                                    } catch (Exception e) {
//                                    }
//                                    
//
//                                } else {
//                                    JOptionPane.showMessageDialog(null, "Password must be the same!");
//                                }
//
//                            }
//
//                        }
//
//                    }
//
//                }
//            }
//        }
    }//GEN-LAST:event_btn_SignUpActionPerformed

//    public String Encrypt(String password) {
//        /* Plain-text password initialization. */
//        String encryptedpassword = null;
//        try {
//            /* MessageDigest instance for MD5. */
//            MessageDigest m = MessageDigest.getInstance("MD5");
//
//            /* Add plain-text password bytes to digest using MD5 update() method. */
//            m.update(password.getBytes());
//
//            /* Convert the hash value into bytes */
//            byte[] bytes = m.digest();
//
//            /* The bytes array has bytes in decimal form. Converting it into hexadecimal format. */
//            StringBuilder s = new StringBuilder();
//            for (int i = 0; i < bytes.length; i++)  
//            {  
//                s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));  
//            }  
//              
//            /* Complete hashed password in hexadecimal format */  
//            encryptedpassword = s.toString();  
//        }   
//        catch (NoSuchAlgorithmException e)   
//        {  
//            e.printStackTrace();  
//        }  
//          
//        /* Display the unencrypted and encrypted passwords. */    
//        return encryptedpassword;  
//    }
    
    private void btn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnActionPerformed
        new login().setVisible(true);
        //dispose();
    }//GEN-LAST:event_btn_ReturnActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Return;
    private javax.swing.JButton btn_SignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JTextField tf_Fname;
    private javax.swing.JTextField tf_Lname;
    private javax.swing.JPasswordField tf_Pass;
    private javax.swing.JTextField tf_Username;
    private javax.swing.JPasswordField tf_confirm;
    // End of variables declaration//GEN-END:variables
}
