/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom4app;

import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author legia
 */
public class TestResult extends javax.swing.JFrame {

    /**
     * Creates new form Result
     */
    public TestResult(int Lesn) {
        initComponents();
        this.count = Lesn;
        this.i = Lesn + 3;
        this.j = i + 2;
        while (count<i) {            
            set("A", this.count);
            count++;
        }
        count = count - 2;
        while (count<j && count>i-3) {
            set("B", this.count);
            count++;   
                }
        lb_Correct.setText(correct+"/6");
    }
    
    int correct = 0;
    int i;
    int j;
    int count;
    int q = 1;
    
    void set(String Tp, int quesNum) {
        try {
            String ID = String.format("%02d", quesNum);
            DBAccess db = new DBAccess();
            DefaultTableModel model = (DefaultTableModel)tb_Result.getModel();
            String query = "Select * From progress"
                    + " Where questionID= '"+ Tp + ID +"'";
            ResultSet rs = db.Query(query);
		if (rs.next()) {
                    if(rs.getString("dapandung").equals(rs.getString("dapandachon"))){
                        model.addRow(new String[]{"Question "+q, "Correct"});
                        q++;
                        correct++;
                    }
                    else{
                        model.addRow(new String[]{"Question "+q, "Wrong"});
                        q++;
                    }
		}	
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Result = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lb_Correct = new javax.swing.JLabel();
        btn_Return = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Result");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        tb_Result.setBackground(new java.awt.Color(204, 255, 255));
        tb_Result.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Question", "Result"
            }
        ));
        jScrollPane1.setViewportView(tb_Result);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 410, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Your correct answer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        lb_Correct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_Correct.setText("4/5");
        getContentPane().add(lb_Correct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        btn_Return.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Return.setText("Return");
        btn_Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/anhnen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReturnActionPerformed
//        try {
//            DBAccess db = new DBAccess();
//            String query = "Delete "
//                    + "From progress";
//            db.Update(query);
//            String query1 = "Select * From logged";
//            ResultSet rs = db.Query(query1);
//            int Lesson = (count - 1)/5;
//            if (rs.next()) {
//                if (correct>4) {
//                    String query3 = "Delete "
//                        + "From userdata Where User='"+rs.getString("User") +"' AND Lesson='"+Lesson+"'";
//                    String query2 = "insert into userdata (User, Lesson, Status)"
//                            + " values('" + rs.getString("User") + "' ,'" + Lesson + "', '" + 1 + "')";
//                    db.Update(query3);
//                    db.Update(query2);
//                    new MainMenu().setVisible(true);
//                    dispose();
//                } else {
//                    String query2 = "insert into userdata (User, Lesson, Status)"
//                            + " values('" + rs.getString("User") + "' ,'" + Lesson + "', '" + 0 + "')";
//                    db.Update(query2);
//                    new MainMenu().setVisible(true);
//                    dispose();
//                }
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_btn_ReturnActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestResult(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Correct;
    private javax.swing.JTable tb_Result;
    // End of variables declaration//GEN-END:variables
}
